---
- name: Install nginx
  hosts: all
  tasks:
   - name: Install nginx
     apt: name=nginx state=latest
     become: true
  # - name: Remove nginx
  #   apt: name=nginx state=absent
  #   become: true
  # - name: Install apache2
  #   apt: name=apache2 state=latest
  #   become: true