---
- hosts: loadbalancer
  tasks:
    #- debug:
    #    msg: "{{ ansible_facts['os_family'] }}"
    - name: patch Windows
      include_tasks: tasks_windows.yaml
      when: ansible_facts['os_family'] == "Windows"
    - name: patch Debian
      include_tasks: tasks_debian.yaml
      when: ansible_facts['os_family'] == "Debian"

    